services:
  web:
    image: "nginx:latest"
    ports: 
      - "6660:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    image: php:8-fpm
    volumes:
      - ./code:/code
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0
    ports:
      - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: helloworld